export const SHOW_PROFILE_EDIT_POPUP = 'SHOW_PROFILE_EDIT_POPUP';
export const HIDE_PROFILE_EDIT_POPUP = 'HIDE_PROFILE_EDIT_POPUP';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_FINISH = 'UPDATE_USER_FINISH';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
